# Varables
PYTHON = python3

# Reglas
all: run

# Prueba para ejecutar un archivo de python con un Makefile
run:
	python central.py

# Limpia los archivos generados durante la compilcion. 
clean:
	rm .rf __pycache__*.pyc
